### ISSUE TITLE
Add a License to Project

### ISSUE THREAD

**Issue by kumar15-sam** [kumar15-sam/github-projects-playground#3]
Hey @iamhirdeshkumar15, I wonder what type of license I should add to this project.

**Comment by iamhirdeshkumar15** [comment]
We usually use an MIT license. I think that would be perfect for this project.

**Comment by iamhirdeshkumar15** [comment]
> Hey @iamhirdeshkumar15, I wonder what type of license I should add to this project.

We usually use an MIT license. I think that would be perfect for this project.

**Comment by kumar15-sam** [comment]
Thanks @iamhirdeshkumar15 , I added License file.
